Repository NeilKleistGao/ts-to-mls, pull requests merged in 2022-08, with the labels that each got.

#22 Add Intersection
  src/main/scala/ts2mls/TSCompilerInfo.scala
  src/main/scala/ts2mls/TSSourceFile.scala
  src/main/scala/ts2mls/types/TSType.scala
  src/test/scala/Intersection.scala
  src/test/scala/Union.scala
  src/test/typescript/Intersection.ts
  src/test/typescript/Union.ts
Labels: enhancement

#23 Update Type Variables in Record Types
  src/main/scala/ts2mls/TSCompilerInfo.scala
  src/main/scala/ts2mls/TSSourceFile.scala
  src/main/scala/ts2mls/types/TSType.scala
  src/test/scala/ClassMember.scala
  src/test/scala/InterfaceMember.scala
  src/test/scala/Intersection.scala
  src/test/scala/TypeVariable.scala
  src/test/scala/Union.scala
  src/test/typescript/ClassMember.ts
  src/test/typescript/InterfaceMember.ts
  src/test/typescript/TypeVariable.ts
Labels: bug

#24 Add Anonymous Interfaces
  src/main/scala/ts2mls/TSCompilerInfo.scala
  src/main/scala/ts2mls/TSSourceFile.scala
  src/main/scala/ts2mls/types/TSType.scala
  src/test/scala/InterfaceMember.scala
  src/test/typescript/InterfaceMember.ts
Labels: bug, enhancement

#25 Add Optional Parameters/Members and ... Parameters Support
  src/main/scala/ts2mls/TSCompilerInfo.scala
  src/main/scala/ts2mls/TSNamespace.scala
  src/main/scala/ts2mls/TSSourceFile.scala
  src/main/scala/ts2mls/types/TSType.scala
  src/test/scala/InterfaceMember.scala
  src/test/scala/Intersection.scala
  src/test/scala/Optional.scala
  src/test/scala/Overload.ts.scala
  src/test/scala/Union.scala
  src/test/typescript/InterfaceMember.ts
  src/test/typescript/Optional.ts
  src/test/typescript/Overload.ts
Labels: enhancement

#27 Add Type Applications
  src/main/scala/ts2mls/TSCompilerInfo.scala
  src/main/scala/ts2mls/TSSourceFile.scala
  src/main/scala/ts2mls/types/TSType.scala
  src/test/scala/ClassMember.scala
  src/test/scala/TypeVariable.scala
  src/test/typescript/Inherit.ts
  src/test/typescript/TypeVariable.ts
Labels: bug, enhancement

#30 Fix Wrong Anonymous Interfaces in Tuples
  src/main/scala/ts2mls/TSSourceFile.scala
  src/test/scala/Tuple.scala
  src/test/typescript/Tuple.ts
Labels: bug

#33 Fix Wrong Type Variables in Tuples
  src/main/scala/ts2mls/TSPrimitive.scala
  src/main/scala/ts2mls/TSSourceFile.scala
  src/test/scala/Tuple.scala
  src/test/typescript/Tuple.ts
Labels: bug

#34 Fix Crash When Parsing Unions in Tuples
  src/test/scala/Tuple.scala
  src/test/typescript/Tuple.ts
Labels: bug, duplicate

#37 Fix default case in class members
  src/main/scala/ts2mls/TSSourceFile.scala
  src/test/scala/Overload.scala
  src/test/typescript/Overload.ts
Labels: bug

#39 Handle `unknown` in `Converter`
  src/main/scala/ts2mls/types/Converter.scala
Labels: enhancement

#40 Distinguish `private`, `protected` and `public` in Classes
  src/main/scala/ts2mls/TSCompilerInfo.scala
  src/main/scala/ts2mls/TSPrimitive.scala
  src/main/scala/ts2mls/TSSourceFile.scala
  src/main/scala/ts2mls/types/Converter.scala
  src/main/scala/ts2mls/types/Field.scala
  src/main/scala/ts2mls/types/TSType.scala
  src/test/scala/ClassMember.scala
  src/test/typescript/ClassMember.ts
Labels: bug, TS Type, Converter

#43 Add Static Class Members Support
  src/main/scala/ts2mls/TSCompilerInfo.scala
  src/main/scala/ts2mls/TSSourceFile.scala
  src/main/scala/ts2mls/types/Converter.scala
  src/main/scala/ts2mls/types/TSType.scala
  src/test/scala/ClassMember.scala
  src/test/typescript/ClassMember.ts
Labels: enhancement, TS Type

#45 Cross Project
  .github/workflows/scala.yml
  build.sbt
  js/src/main/scala/Main.scala
  js/src/main/scala/mlscript/syntax.scala
  js/src/main/scala/mlscript/utils/shorthands.scala
  js/src/main/scala/ts2mls/TSCompilerInfo.scala
  js/src/main/scala/ts2mls/TSNamespace.scala
  js/src/main/scala/ts2mls/TSPrimitive.scala
  js/src/main/scala/ts2mls/TSProgram.scala
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/main/scala/ts2mls/types/Converter.scala
  js/src/main/scala/ts2mls/types/Field.scala
  js/src/main/scala/ts2mls/types/Module.scala
  js/src/main/scala/ts2mls/types/TSType.scala
  js/src/test/scala/Array.scala
  js/src/test/scala/BasicFunction.scala
  js/src/test/scala/ClassMember.scala
  js/src/test/scala/EmptyTest.scala
  js/src/test/scala/Enum.scala
  js/src/test/scala/HighOrderFunc.scala
  js/src/test/scala/InterfaceMember.scala
  js/src/test/scala/Intersection.scala
  js/src/test/scala/MultiFiles.scala
  js/src/test/scala/NameSpace.scala
  js/src/test/scala/Optional.scala
  js/src/test/scala/Overload.scala
  js/src/test/scala/Tuple.scala
  js/src/test/scala/TypeCompare.scala
  js/src/test/scala/TypeVariable.scala
  js/src/test/scala/Union.scala
  js/src/test/typescript/Array.ts
  js/src/test/typescript/BasicFunctions.ts
  js/src/test/typescript/ClassMember.ts
  js/src/test/typescript/Enum.ts
  js/src/test/typescript/HighOrderFunc.ts
  js/src/test/typescript/Inherit.ts
  js/src/test/typescript/InterfaceMember.ts
  js/src/test/typescript/Intersection.ts
  js/src/test/typescript/Multi1.ts
  js/src/test/typescript/Multi2.ts
  js/src/test/typescript/NameSpace.ts
  js/src/test/typescript/Optional.ts
  js/src/test/typescript/Overload.ts
  js/src/test/typescript/Tuple.ts
  js/src/test/typescript/TypeVariable.ts
  js/src/test/typescript/Union.ts
  project/plguins.sbt
Labels: bug

#48 Throw When File Does Not Exist
  js/src/main/scala/ts2mls/TSProgram.scala
  js/src/test/scala/ts2mls/WrongPath.scala
Labels: bug

#50 Add Debugging
  .github/workflows/scala.yml
  js/src/main/scala/ts2mls/DecWriter.scala
  js/src/main/scala/ts2mls/TSCompilerInfo.scala
  js/src/main/scala/ts2mls/TSNamespace.scala
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/main/scala/ts2mls/types/TSType.scala
  js/src/test/diff/BasicFunctions.d.mls
  js/src/test/diff/ClassMember.d.mls
  js/src/test/diff/Enum.d.mls
  js/src/test/diff/Inherit.d.mls
  js/src/test/diff/InterfaceMember.d.mls
  js/src/test/diff/Namespace.d.mls
  js/src/test/diff/Overload.d.mls
  js/src/test/diff/Tuple.d.mls
  js/src/test/diff/TypeVariable.d.mls
  js/src/test/scala/ts2mls/Enum.scala
  js/src/test/typescript/BasicFunctions.ts
  js/src/test/typescript/ClassMember.ts
  js/src/test/typescript/InterfaceMember.ts
  js/src/test/typescript/NameSpace.ts
Labels: enhancement, TS Type, Converter

#53 Fix CI
  .github/workflows/scala.yml
Labels: bug

#58 Reformat converter output
  build.sbt
  js/src/main/scala/ts2mls/DecWriter.scala
  js/src/main/scala/ts2mls/TSNamespace.scala
  js/src/main/scala/ts2mls/TSProgram.scala
  js/src/main/scala/ts2mls/types/Converter.scala
  js/src/main/scala/ts2mls/types/Field.scala
  js/src/main/scala/ts2mls/types/TSType.scala
  js/src/test/diff/Array.d.mls
  js/src/test/diff/BasicFunctions.d.mls
  js/src/test/diff/ClassMember.d.mls
  js/src/test/diff/Enum.d.mls
  js/src/test/diff/HighOrder.d.mls
  js/src/test/diff/Inherit.d.mls
  js/src/test/diff/InterfaceMember.d.mls
  js/src/test/diff/Intersection.d.mls
  js/src/test/diff/MultiFiles.d.mls
  js/src/test/diff/Namespace.d.mls
  js/src/test/diff/Optional.d.mls
  js/src/test/diff/Overload.d.mls
  js/src/test/diff/Tuple.d.mls
  js/src/test/diff/TypeVariable.d.mls
  js/src/test/diff/Union.d.mls
  js/src/test/typescript/Intersection.ts
Labels: bug, Converter

#60 Use Nominal Typing in Hierachy
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/main/scala/ts2mls/types/Converter.scala
  js/src/main/scala/ts2mls/types/TSType.scala
  js/src/test/diff/Inherit.d.mls
  js/src/test/diff/InterfaceMember.d.mls
Labels: bug, TS Type, Converter

#61 Fix Unused Type Variables
  js/src/test/diff/Optional.d.mls
  js/src/test/diff/Overload.d.mls
  js/src/test/typescript/Optional.ts
  js/src/test/typescript/Overload.ts
Labels: bug, Converter

#62 Fix Enum Conversion
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/test/diff/Enum.d.mls
  js/src/test/diff/InterfaceMember.d.mls
  js/src/test/diff/Namespace.d.mls
Labels: bug, TS Type, Converter

#56 Fix Namespace Parser
  js/src/main/scala/ts2mls/TSCompilerInfo.scala
  js/src/main/scala/ts2mls/TSNamespace.scala
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/test/diff/Namespace.d.mls
Labels: bug, TS Type

#69 Sort Outputs
  js/src/main/scala/ts2mls/DecWriter.scala
  js/src/main/scala/ts2mls/TSNamespace.scala
  js/src/test/diff/Array.d.mls
  js/src/test/diff/BasicFunctions.d.mls
  js/src/test/diff/ClassMember.d.mls
  js/src/test/diff/Enum.d.mls
  js/src/test/diff/HighOrder.d.mls
  js/src/test/diff/Inherit.d.mls
  js/src/test/diff/InterfaceMember.d.mls
  js/src/test/diff/Intersection.d.mls
  js/src/test/diff/MultiFiles.d.mls
  js/src/test/diff/Namespace.d.mls
  js/src/test/diff/Optional.d.mls
  js/src/test/diff/Overload.d.mls
  js/src/test/diff/Tuple.d.mls
  js/src/test/diff/TypeVariable.d.mls
  js/src/test/diff/Union.d.mls
  js/src/test/typescript/Multi1.ts
  js/src/test/typescript/Multi2.ts
Labels: bug, Converter

#70 Fix Check With Undefined Type Node
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/test/diff/Intersection.d.mls
  js/src/test/typescript/Intersection.ts
Labels: bug, TS Type

#73 Fix Type Variables in Classes/Interfaces
  js/src/main/scala/ts2mls/TSCompilerInfo.scala
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/main/scala/ts2mls/types/Converter.scala
  js/src/test/diff/ClassMember.d.mls
  js/src/test/diff/Inherit.d.mls
  js/src/test/diff/InterfaceMember.d.mls
  js/src/test/typescript/ClassMember.ts
  js/src/test/typescript/Inherit.ts
  js/src/test/typescript/InterfaceMember.ts
Labels: bug, TS Type

#74 Fix Nominal and Structrural Types
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/test/diff/Array.d.mls
  js/src/test/diff/BasicFunctions.d.mls
  js/src/test/diff/Intersection.d.mls
  js/src/test/diff/Overload.d.mls
  js/src/test/diff/Tuple.d.mls
  js/src/test/typescript/BasicFunctions.ts
  js/src/test/typescript/Intersection.ts
Labels: bug, TS Type, Converter

#78 Fix Overload
  js/src/main/scala/ts2mls/TSCompilerInfo.scala
  js/src/main/scala/ts2mls/TSNamespace.scala
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/test/diff/Overload.d.mls
  js/src/test/typescript/Overload.ts
Labels: bug, TS Type

#79 Fix `any[]` in Rest Parameters
  js/src/main/scala/ts2mls/TSCompilerInfo.scala
  js/src/main/scala/ts2mls/TSSourceFile.scala
  js/src/test/diff/Optional.d.mls
  js/src/test/typescript/Optional.ts
Labels: bug, TS Type

#81 Add Method Type Variables and Overload
  js/src/main/scala/ts2mls/TSNamespace.scala
  js/src/main/scala/ts2mls/types/Converter.scala
  js/src/main/scala/ts2mls/types/TSType.scala
  js/src/test/diff/Overload.d.mls
  js/src/test/diff/TypeVariable.d.mls
  js/src/test/typescript/Overload.ts
  js/src/test/typescript/TypeVariable.ts
Labels: bug, enhancement, Converter

#82 Fix Test
  js/src/test/diff/TypeVariable.d.mls
  js/src/test/typescript/TypeVariable.ts
Labels: invalid

#85 Merge Namespaces in Different Files
  js/src/main/scala/ts2mls/TSNamespace.scala
  js/src/test/diff/MultiFiles.d.mls
  js/src/test/typescript/Multi1.ts
  js/src/test/typescript/Multi2.ts
  js/src/test/typescript/Multi3.ts
Labels: bug, TS Type
